routes/web.php
<?php

use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [PostController::class, 'home'])->name('home');
Route::get('/all-post', [PostController::class, 'showAllPosts'])->name('show-all');
Route::get('/login', [UserController::class, 'login'])->name('login');
Route::post('/signin', [UserController::class, 'signin'])->name('signin');
Route::get('/register', [UserController::class, 'register'])->name('register');
Route::post('/signup', [UserController::class, 'signup'])->name('signup');
Route::get('post/{slug}', [PostController::class, 'show'])->where('slug', '[A-Za-z0-9-_]+')->name('view-post');
//Route::get('consume', [PostController::class, 'getResultFromAPI'])->name('consume-api');

Route::middleware(['auth'])->group(function () {
    Route::get('/logout', [UserController::class, 'logout'])->name('logout');
    Route::get('new-post', [PostController::class, 'newPost'])->name('new-post');
    Route::post('persist-post', [PostController::class, 'persistPost'])->name('save-post');
    Route::get('user/{id}', [UserController::class, 'profile'])->where('id', '[0-9]+')->name('user-profile');
    Route::get('posts/user/{id}', [PostController::class, 'myPosts'])->where('id', '[0-9]+')->name('my-posts');
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;

class Post extends Model
{
    use HasFactory;

    public $timestamps = false;

    /**
     * Restricted columns from modifying
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * Return the author with the post belongs to
     *
     * @author  Cayetano H. Osma <chernandez@elestadoweb.com>
     * @version Nov 2020
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function author()
    {
        return $this->belongsTo(User::class, 'author_id', 'id');
    }

    /**
     * Set the Slug attribute and the title as well.
     *
     * @author  Cayetano H. Osma <chernandez@elestadoweb.com>
     * @version Nov 2020
     *
     * @param $value
     */
    public function setTitleAttribute($value)
    {
        $this->attributes['title'] = $value;
        $this->attributes['slug'] = Str::slug($value);
    }

    /**
     * Return the publish date formatted to show in the page.
     *
     * @author  Cayetano H. Osma <chernandez@elestadoweb.com>
     * @version Nov 2020
     *
     * @param $value
     *
     * @return string
     */
    public function getPublishDateAttribute($value)
    {
        return (Carbon::createFromFormat('Y-m-d H:i:s', $value))->toFormattedDateString();
    }

}

resources/views/includes/menu.blade.php
<hr />
<div class="row">
    <ul class="nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{{ route('home') }}">Home</a>
        </li>
    </ul>
    <ul class="nav ml-auto">
        @if (!Auth::guest())
            <li class="nav-item">
                <a class="nav-link active" href="{{ route('new-post') }}">New post</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{{ route('show-all') }}" alt="Show all posts">Show all posts</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{{ route('home') }}" alt="Show all posts">Show my posts</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{{ route('logout') }}#">Logout</a>
            </li>
        @else
            <li class="nav-item">
            <a class="nav-link" href="{{ route('register') }}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('login') }}">Login</a>
            </li>
        @endif
    </ul>
</div>
<hr />

resources/views/includes/showPost.blade.php
<div class="col-12">
    <div class="card mt-2 mx-auto">
        <div class="card-body">
            <h5 class="card-title">
                <a class="h2" href="{{ route('view-post', $post->slug) }}" alt="view-post">{{ $post->title }}</a>
            </h5>
            <p class="card-text">{{ mb_strimwidth($post->description, 0, 250, "...") }}</p>
            <div class="float-right">
                <h6 class="card-subtitle text-muted">
                    {{ $post->author->name }}, {{ $post->publish_date }}
                </h6>
            </div>
        </div>
    </div>
</div>